// <auto-generated />
using Hoshiko.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hoshiko.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251112094307_InitialSeed")]
    partial class InitialSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Hoshiko.Data.Entities.Stage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Stages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "این یک مرحله‌ی نمونه است برای تست سیستم.",
                            Title = "مرحله آزمایشی"
                        });
                });

            modelBuilder.Entity("Hoshiko.Data.Entities.StageSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CorrectAnswer")
                        .HasColumnType("TEXT");

                    b.Property<string>("OptionA")
                        .HasColumnType("TEXT");

                    b.Property<string>("OptionB")
                        .HasColumnType("TEXT");

                    b.Property<string>("OptionC")
                        .HasColumnType("TEXT");

                    b.Property<string>("OptionD")
                        .HasColumnType("TEXT");

                    b.Property<int>("StageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StageId");

                    b.ToTable("StageSections");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            StageId = 1,
                            Text = "در این بخش یاد می‌گیریم چطور مراحل بازی کار می‌کنند.",
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            StageId = 1,
                            Text = "هر مرحله دارای چند توضیح و چند سوال است.",
                            Type = 0
                        },
                        new
                        {
                            Id = 3,
                            CorrectAnswer = "B",
                            OptionA = "دو بخش",
                            OptionB = "چهار بخش",
                            OptionC = "یک بخش",
                            OptionD = "پنج بخش",
                            StageId = 1,
                            Text = "چند بخش در هر مرحله وجود دارد؟",
                            Type = 1
                        },
                        new
                        {
                            Id = 4,
                            CorrectAnswer = "C",
                            OptionA = "به مرحله بعد می‌روی",
                            OptionB = "بازی ریست می‌شود",
                            OptionC = "پاسخ خط می‌خورد و ادامه می‌دهی",
                            OptionD = "هیچ‌چیز",
                            StageId = 1,
                            Text = "اگر پاسخ اشتباه بدهی چه می‌شود؟",
                            Type = 1
                        });
                });

            modelBuilder.Entity("Hoshiko.Data.Entities.StageSection", b =>
                {
                    b.HasOne("Hoshiko.Data.Entities.Stage", "Stage")
                        .WithMany("Sections")
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stage");
                });

            modelBuilder.Entity("Hoshiko.Data.Entities.Stage", b =>
                {
                    b.Navigation("Sections");
                });
#pragma warning restore 612, 618
        }
    }
}
